version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tracio
      MYSQL_USER: tracio_user
      MYSQL_PASSWORD: tracio_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

volumes:
  mysql_data:
